title: Bear King's Stronghold
author: th3_5had0w
subtitle: The life of a suffering bear

url: "https://th3-5had0w.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "#"
footer_text: "Fixed by th3_5had0w"

profile-picture: assets/profile.gif
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "#"
