title: Bear king stronghold
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://th3-5had0w.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://github.com/rahul-bothra"
footer_text: "Theme by rahul-bothra"

profile-picture: assets/profile.gif
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://rahul-bothra.github.io/CV.pdf"
